[package]
name = "calculator-app"
version = "0.1.0"
authors = ["landenb"]
edition = "2021"
build = "build.rs"
description = "Calculator app built with Rust and Slint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0"

[build-dependencies]
slint-build = "1.0"

[package.metadata.bundle]
name = "Rust Calculator"
identifier = "io.github.cubelube.slint-calculator-app"
icon = ['./calculator.png']
